stages:
  split:
    cmd: python src/data/data_splitting.py
    deps:
    - data/raw_data/raw.csv
    - src/data/data_splitting.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/data_normalization.py
    deps:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - src/data/data_normalization.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  grid-search:
    cmd: python src/data/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/data/grid_search.py
    outs:
    - models/ridge_linear_regression.pkl
  train:
    cmd: python src/models/training.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/training.py
    - models/ridge_linear_regression.pkl
    outs:
    - models/ridge_linear_regression_trained.pkl
  evaluate:
    cmd: python src/models/evaluation.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
    - src/models/evaluation.py
    - models/ridge_linear_regression_trained.pkl
    outs:
    - metrics/scores.json
